# Test YAML file with multiple issues for XPRR testing
# This file contains intentional formatting and validation issues

apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
  # Missing labels
  # Missing annotations
data:
  key1: value1
  key2: value2
  # Missing proper structure
  # Missing documentation

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 3  # Magic number
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test-container
        image: nginx:latest
        # Missing resource limits
        # Missing security context
        # Missing health checks
        ports:
        - containerPort: 80
          # Missing protocol
          # Missing name

---
# Invalid YAML structure
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: test
    # Missing proper selector structure 