# Default configuration for x-pull-request-reviewer
llm:
  # Primary LLM provider to use (ollama, google_code_assist, gemini_cli)
  provider: gemini_cli
  
  # Provider-specific configurations
  providers:
    ollama:
      host: localhost
      port: 11434
      model: codellama-trained-20250624_193347
      timeout: 30
    
    google_code_assist:
      model: gemini-1.5-flash
      temperature: 0.1
      max_tokens: 2048
      timeout: 30
    
    gemini_cli:
      timeout: 60
      auto_install: true

github:
  token: your_github_token_here
  api_url: https://api.github.com

agent:
  mode: background
  log_level: INFO
  
  # Review settings
  review:
    max_diff_size: 10000  # Maximum diff size in characters
    chunk_size: 4000      # Chunk size for large diffs
    enable_interactive: true
    post_comments: true
    
  # Security settings
  security:
    enabled: true
    severity_levels: [critical, high, medium, low]
    
  # Compliance settings
  compliance:
    enabled: true
    check_license: true
    check_copyright: true
    
  # Best practices settings
  best_practices:
    enabled: true
    language_specific: true 