# Default configuration for x-pull-request-reviewer
llm:
  provider: ollama
  model: codellama-trained-20250624_193347
  port: 11434
github:
  token: your_github_token_here
  api_url: https://api.github.com
agent:
  mode: background
  log_level: INFO 